"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, ArrowLeft, Eye } from 'lucide-react';
import Link from 'next/link';

export default function MedicalDisclaimerPage() {
    return (
        <div className="min-h-screen bg-gray-50 flex flex-col">
            {/* Header / Navbar */}
            <nav className="fixed w-full z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between h-16 items-center">
                        <Link href="/" className="flex items-center space-x-2">
                            <div className="bg-blue-600 p-2 rounded-lg text-white">
                                <Eye size={20} />
                            </div>
                            <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">
                                Smart Eye Care
                            </span>
                        </Link>
                        <Link href="/" className="text-sm font-medium text-gray-500 hover:text-gray-900 flex items-center">
                            <ArrowLeft size={16} className="mr-2" /> Back to Home
                        </Link>
                    </div>
                </div>
            </nav>

            <main className="flex-grow pt-32 pb-20 px-4">
                <div className="max-w-3xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="bg-white p-8 md:p-12 rounded-[40px] shadow-sm border border-gray-100"
                    >
                        <div className="w-16 h-16 bg-red-100 text-red-600 rounded-2xl flex items-center justify-center mb-8">
                            <ShieldAlert size={32} />
                        </div>

                        <h1 className="text-4xl font-black text-slate-900 mb-6">Medical Disclaimer</h1>

                        <div className="space-y-6 text-gray-600 leading-relaxed text-lg">
                            <p className="font-bold text-slate-900">
                                This application ("Smart Eye Care") provides an AI-powered screening tool for educational and informational purposes only.
                            </p>

                            <p>
                                1. <span className="font-bold text-slate-900">No Professional Advice:</span> The information provided by this system, including prediction labels, heatmaps, and confidence scores, does not constitute professional medical advice, diagnosis, or treatment.
                            </p>

                            <p>
                                2. <span className="font-bold text-slate-900">Not a Diagnostic Tool:</span> Results generated by our deep learning models are intended to assist healthcare providers and labs in flagging potential issues for manual review. They are NOT definitive diagnoses.
                            </p>

                            <p>
                                3. <span className="font-bold text-slate-900">Consult a Professional:</span> Patients should never use this application as a substitute for an in-person examination by a qualified ophthalmologist or optometrist. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                            </p>

                            <p>
                                4. <span className="font-bold text-slate-900">Limitation of Liability:</span> Smart Eye Care Lab and its developers are not liable for any decisions made or actions taken based on the output of this screening tool. Reliance on any information provided by the software is solely at your own risk.
                            </p>
                        </div>

                        <div className="mt-12 pt-8 border-t border-gray-100">
                            <Link href="/register">
                                <button className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold hover:bg-blue-700 transition-colors shadow-lg">
                                    I Understand, Proceed to App
                                </button>
                            </Link>
                        </div>
                    </motion.div>
                </div>
            </main>

            {/* Footer */}
            <footer className="py-12 bg-white border-t border-gray-100">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center text-gray-400 text-sm font-medium">
                    <div>© 2026 Smart Eye Care Lab. All rights reserved.</div>
                    <div className="flex space-x-6 mt-6 md:mt-0">
                        <Link href="/medical-disclaimer" className="hover:text-red-500 font-medium">Medical Disclaimer</Link>
                        <Link href="/privacy-policy" className="hover:text-gray-600">Privacy Policy</Link>
                        <Link href="/terms-of-service" className="hover:text-gray-600">Terms of Service</Link>
                    </div>
                </div>
            </footer>
        </div>
    );
}
